language: node_js
node_js:
  - "7.1"
#addons:
#  sauce_connect: true
cache:
  directories:
    #- $HOME/.yarn-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.npm
    - $HOME/.android/build-cache        
matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      sudo: required
      node_js: false
      android:
        components:
          - tools
          - build-tools-23.0.1
          #- build-tools-25.0.2
          - android-23
          #- android-25
          #- extra-android-m2repository
          #- extra-google-google_play_services
          #- extra-google-m2repository
          #- addon-google_apis-google-16
        licenses:
          - '.+'
      script:
        - nvm install v7.1
        - node --version
        #- npm i react -g
        - npm i react-native-cli -g
        #- npm i npm react-native-easy-grid -g
        - npm install && react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/build/intermediates/res/merged/debug        
        - cd android && ./gradlew assembleDebug && cd .. 
        #&& ./gradlew assembleRelease
      after_success:
          - npm install webdriverio
          - npm install wdio-sauce-service --save-dev
          - ./node_modules/.bin/wdio wdio.conf.js
          #- curl -sL http://monkop.com/cli -o monkop-cli.py
          #- ls $TRAVIS_BUILD_DIR/android/app/build/outputs/apk/
          #- python monkop-cli.py -k $monkopapikey -w -t 3 -a "$TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app-debug.apk" 
      #before_deploy:
      #- cp $TRAVIS_BUILD_DIR/debug.keystore $HOME
      #- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 $TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app-release-unsigned.apk androiddebugkey -keystore $HOME/debug.keystore -storepass $storepass -keypass $keypass
      #- "${ANDROID_HOME}/build-tools/23.0.1/zipalign 4 $TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app-release-unsigned.apk $TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app-debug-signed.apk"
      #deploy: # mostly generated by `> travis deploy releases`
      #  skip_cleanup: true
      #  provider: releases
      #  api_key:
      #    secure: 2fYSjSPMmTUDhcgd6w/nXVMtsp6O+GHb0gFjpTjPA33xodEYsNlEvmdk9fvUJakWi2z0VxBaGw1iHaYCQmzj8858caQVjlSpdTRUVw3d/CMw0O3kZWKD37GaX5ocY1LZ2QSJS1ePXitOZYkgqbfK104Tiuru1/SKKziLgM5OIHVQj4CGdlvqRr5rERU2Sy9yPi+XgrlnTgcNGIzZ+3In19jhaZzFLvVTQckk0R6oQaQQnt/GudEPdft2SNLQS0ecHuUj8n8dGb0TR2G9ej5gVq7aDo4oyn2k8FOKa86XwT6cGpjm3VdOb5rfvAVxglm4GqWWjxXkm8Wq69Awrhb6PDHGvq1H68ShvEudSPr1ABRj6grWsf8n5IxKQL4FG+pV2d3D6wtD/mnljguvCjw8Gb652VFwij/Vhm4z8W/VvviUXF+sWnivdEOgvUOG3XW9DZP84I1IWPLSfj2nVnmgVYJVIrCmcSWh2B2iednJeWP75mz5PyXfUp+Q9ECuu0C19oi7C2pTHTqq3GhXAhtZszmllW4cRftw7kUYsyzDzVutB8SVSkKqSCiO/NXIfvbaHQ1BHabzV5aAhD1n2fitB7UDROaXZSlAWzq2eSpbKzITHmkUateEgig89oDIE9NUJ/iITTtWzGjqTxwQkhpFWN6HUSIJleC0658kgI/izwI=
      #  file: $TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app-debug-signed.apk
      #  on:
      #    repo: CodeLanka/ez-net-app
      #    tags: true
    #- language: objective-c
    #  os: osx
    #  osx_image: xcode8.2
    #  node_js: false
    #  before_install:
    #    - nvm install 7
    #    - node --version
    #    - travis_retry npm install -g yarn
    #    - yarn -version
    #  install:
    #    - travis_retry gem install xcpretty
    #    - travis_retry yarn
    #  xcode_project: ios/ReactNativeProject.xcodeproj
    #  xcode_scheme: ios/ReactNativeProjectTests
    #  script:
    #    - cd ios
    #    - xcodebuild -scheme ReactNativeProject -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
